[package]
name = "save-message"
version = "1.0.0"
authors = []

[addresses]
dev = "_"

[dev-addresses]
dev = "0xC0FFEE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
